Wed Nov 17 11:54:40 2021
Darwin-20.4.0-x86_64-i386-64bit
Ren'Py 7.4.10.2178
 

Bootstrap to the start of init.init took 0.19s
Early init took 0.02s
Loader init took 0.08s
Loading error handling took 0.13s
Loading script took 0.60s
Loading save slot metadata. took 0.35s
Loading persistent took 0.00s
Importing _renpysteam: ImportError('No module named _renpysteam',)
Running init code took 0.13s
Loading analysis data took 0.04s
Analyze and compile ATL took 0.01s
Index archives took 0.00s
Backing up script files to '/Users/benceleventebodo/Library/RenPy/backups/eastern_medicine_project':
Dump and make backups. took 0.39s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc. took 0.04s
DPI scale factor: 1.000000
Creating interface object took 0.00s
Cleaning stores took 0.00s
Init translation took 0.08s
Build styles took 0.01s
Load screen analysis took 0.01s
Analyze screens took 0.03s
Save screen analysis took 0.07s
Prepare screens took 0.10s
Save pyanalysis. took 0.00s
Save bytecode. took 0.06s
Running _start took 0.00s
Performance test:
Interface start took 0.37s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1440, 900)
swap interval: 1 frames
Fullscreen mode.
Vendor: 'Intel Inc.'
Renderer: 'Intel HD Graphics 5000 OpenGL Engine'
Version: '2.1 INTEL-16.2.16'
Display Info: None
Screen sizes: virtual=(1920, 1080) physical=(1440, 900) drawable=(1440, 900)
Maximum texture size: 4096x4096
Test message for creating a character and calling a function from a .py file
Almos

Full traceback:
  File "game/script.rpy", line 22, in script call
    call defeat_mid_interogation
  File "game/script.rpy", line 112, in script
    with dissolve(3.0) #TODO for some reasion this here is not callable
  File "/Applications/renpy-7.4.10-sdk/renpy/ast.py", line 1443, in execute
    renpy.exports.with_statement(trans, paired)
  File "/Applications/renpy-7.4.10-sdk/renpy/exports.py", line 1682, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "/Applications/renpy-7.4.10-sdk/renpy/display/core.py", line 2752, in do_with
    clear=clear)
  File "/Applications/renpy-7.4.10-sdk/renpy/display/core.py", line 3315, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "/Applications/renpy-7.4.10-sdk/renpy/display/core.py", line 3674, in interact_core
    new_widget=layers_root)
TypeError: 'Dissolve' object is not callable

While running game code:
  File "game/script.rpy", line 22, in script call
    call defeat_mid_interogation
  File "game/script.rpy", line 112, in script
    with dissolve(3.0) #TODO for some reasion this here is not callable
TypeError: 'Dissolve' object is not callable
